version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "deploy":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run:
          name: Deploy
          command: npm run deploy
      - run:
          name: Update version on GCS
          command: |
            echo Updating to version $(cat latest-chrome-player-version)
            gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
            gsutil cp latest-chrome-player-version gs://install-versions.risevision.com
            gsutil setmeta -h "Cache-Control:private, max-age=0" gs://install-versions.risevision.com/latest-chrome-player-version
            gsutil setmeta -h "Content-Type:text/plain" gs://install-versions.risevision.com/latest-chrome-player-version
            gsutil acl ch -u AllUsers:R gs://install-versions.risevision.com/latest-chrome-player-version

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - "test"
      - "deploy":
          requires:
            - test
          filters:
            branches:
              only:
                - master
