version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "deploy":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - "test"
      - "deploy":
          requires:
            - test
          filters:
            branches:
              only:
                - master
